service: serverless-fiap-test

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    AWS_ROLE_ARN: ${env:AWS_ROLE_ARN}
  iam:
    role: ${env:AWS_ROLE_ARN}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
