service: serverless-fiap-test

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  # profile: fiap-pos
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    AWS_ROLE_ARN: ${env:AWS_ROLE_ARN}
  roleArn: ${env:AWS_ROLE_ARN}
  # Use a role IAM existente do AWS Academy
  #: arn:aws:iam::362400434396:role/LabRole
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
