service: serverless-fiap-test

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  # profile: fiap-pos
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${opt:stage, 'dev'}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
